apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-runner-maven-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Pi
  mountOptions:
  - nolock,noresvport,noacl,hard
  - vers=3
  - rsize=1048576
  - wsize=1048576
  - proto=tcp
  - timeo=600
  - retrans=2
  nfs:
    path: /share
    server: 25aff249d58-wdg89.ap-northeast-1.nas.aliyuncs.com
