apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-maven-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Pi
  volumeName: gitlab-runner-maven-pv
